version: "3.9"

services:
    mongodb:
        container_name: chat-mongo-db
        image: mongo:6-jammy
        ports:
            - '${MONGO_PORT}:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - backend

volumes:
    mongodb_data:


networks:
    backend:
        driver: bridge